[sample_1]
cmd = "../../HW1/build/tools/main/main ../../HW1/test/test1"
answer = "./test1.out"

[sample_2]
cmd = "../../HW1/build/tools/main/main ../../HW1/test/test2"
answer = "./test2.out"

[sample_3]
cmd = "../../HW1/build/tools/main/main ../../HW1/test/test3"
answer = "./test3.out"

[sample_4]
cmd = "../../HW1/build/tools/main/main ../../HW1/test/test4"
answer = "./test4.out"

[simple_test_1]
cmd = "../../HW1/build/tools/main/main ./simple_test_1"
answer = "./simple_test_1.out"

[deepseek_test_1]
cmd = "../../HW1/build/tools/main/main ./deepseek_test_1"
answer = "./deepseek_test_1.out"

[signed_overflow]
cmd = "../../HW1/build/tools/main/main ./signed_overflow"
answer = "./signed_overflow.out"

[division_by_zero]
cmd = "../../HW1/build/tools/main/main ./division_by_zero"

[is_your_program_slow]
cmd = "../../HW1/build/tools/main/main ./slow"
